image: node:10.14.2-alpine

cache: 
  paths:
    - node_modules/

before_script: 
  - npm install -g @vue/cli

stages:
  - test
  - production

test_build:
  stage: test
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist
  
productions:
  stage: production
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist